{% set name = "mhfp" %}
{% set version = "1.9.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 646909a166d3b0e375c4497f653be45fe6e086ae9214e251b4a85c5ca9b6ad42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - rdkit
    - numpy

test:
  imports:
    - mhfp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mhfp/
  summary: Molecular MHFP fingerprints for cheminformatics applications
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - hadim
